title: Joey Galino # your name (or website title) here
logo: "499.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Front End Wizard
  <a href="https://www.linkedin.com/in/joseph-galino-9a3b71190/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
